version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile : Dockerfile
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=supersecret
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
